### ISSUE TITLE
Support range filters

### ISSUE THREAD

**Issue by ripa1995** [runtime-machines/sql2vm#3]
## Motivations

VASe supports also SELECT statements that include a WHERE condition that is using `>`, `<`, `>=`, `<=` ~~and BETWEEN~~.

- Would you like to implement this feature? [y/n] Y

## Solution

Modify `filter.rs` such that it supports the filters mentioned above.

**Comment by ripa1995** [comment]
@erikareale, also `BETWEEN` should be accepted, correct?

**Comment by erikareale** [comment]
> 

Since it is better to check the composition (AND/OR) of more range proofs, it's better to avoid BETWEEN for the MVP
